
# COMMENT --------------------------------------------------

# use comments and seperator



FILE_TYPE           : obj
CHAR_NAME           : cal
NEUTRAL             : callum_neutral


PATH:
  FOLDER            : E:/sgScripts/project
  FACE_SHAPES       : /model/face/l_r_faceShapes
  OUT_BLEND         : /model/face/faceBlended/
  GUIDES            : /guide/
  IN_BLEND          : /model/face/faceBlended/bsMan_blendNode.ma
  HEAD              : /model/face/faceNeutralShape


NAME:
  HEAD              : C_body_PLY
  FACE_SHAPES_GEO   : "bsMan_fRig_PLY"
  FACE_GEO          : "C_head_low_PLY"
  BSMAN_NAME        : "bsMan_blendNode"


